/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ", the newly elected mayor, welcome you to our beautiful city. The place where people from all walks of life find their happiness and where all dreams come true.": "各行各业的人们找到幸福的地方，所有梦想成真的地方。",
    "100 Citizen": "100公民",
    "Come and be a citizen today!": "今天就来成为一名公民吧！",
    "DELETE SAVE": "删除存档",
    "Edward Rush": "Edward Rush",
    "On behalf of the proud citizens of": "我代表自豪的公民",
    "PLAY (R)": "开始 (R)",
    "PLAY AGAIN (R)": "重玩 (R)",
    "RESUME GAME": "返回游戏",
    "START NEW GAME": "开始新游戏",
    "Welcome to SáruCity": "欢迎来到萨鲁城",
    ". Can I see your papers and identification?": ". 我可以看看你的证件和身份证吗？",
    "(Officer Saeki)": "（Saeki警官）",
    "Also, here's a form you have to sign:": "此外，这是一张您必须签署的表格：",
    "and welcome to": "并欢迎来到",
    "Boy": "男",
    "Bro": "兄弟",
    "Citizen Identifier": "公民身份识别码",
    "Citizen Name": "公民姓名",
    "Dude": "伙计",
    "Girl": "女",
    "Hi, my name is": "嗨，我的名字是",
    "How you prefer to be called?": "你更喜欢别人怎么称呼你？",
    "Officer Saeki": "Saeki警官",
    "SC Border Patrol": "SC 边境巡逻队",
    "She/Her": "她",
    "They/Them": "他们",
    "Sure, here it is, officer": "当然，在这里，警官",
    "He/Him": "他",
    "Gurl": "女孩",
    "Mate": "小老弟",
    "SáruCity": "萨鲁市",
    "Gal": "姑娘",
    "Bruh": "兄弟",
    ", bro, been waiting for you forever... and look at you, you still look ugly as hell!": "兄弟，一直在等着你……看你的样子，还是丑死了！",
    ", your profile looks good to me... Here's your papers. You're good to go. The exit is that way... Have a good day!": "，我觉得你的个人资料不错……这是你的论文。 你可以开始了。 出口在那边……祝你有美好的一天！",
    "(Hamlet)": "（村庄）",
    "*sigh*": "*感叹*",
    "All I can tell you is that the situation here has spiralled out of control since the new mayor got elected. But enough with the sad talk... you just got here after all. Let's go eat something. I know a decent bar...": "但悲伤的谈话已经够多了……毕竟你才刚到这里。 我们去吃点东西吧。 我知道一个不错的酒吧...",
    "Alright,": "好的，",
    "And you're not?": "难道你不是吗？",
    "by Ivma": "作者 Ivma",
    "Hey,": "嘿，",
    "I missed you too, Ham": "我也很想你，哈姆",
    "Is it really that bad?": "真的那么糟糕吗？",
    "Nah, I'm just kidding, I missed you, bro. It's been really tough here without family...": "不，我只是在开玩笑，我想你了，兄弟。 没有家人在这里真的很难受...",
    "Okay": "好的",
    "Okay, let's go.": "好吧，我们走吧。",
    "Outside the SCBP": "在 SCBP 之外",
    "Thank you, officer": "谢谢你，警官",
    "Thanks bro, really appreciate it.": "谢谢老哥，真的很感激。",
    "You can sleep in the car while I drive, you must be tired...": "我开车的时候你可以在车里睡，你一定很累吧……",
    "You can't trust anyone in this city. Everyone seems to be in a race, like rats...": "在这个城市，你不能相信任何人。 每个人似乎都在赛跑，像老鼠一样……",
    "Zero": "零",
    "Okay... so here's the good part. Everytime you win, it's being recorded... and those will add up to your winnings. That means, if you've won 3 times before, and you win again, you'll be getting 4 dollars instead of 1 and so on... and it doesn't have to be a win streak.": "好的...所以这是好的部分。 每次您赢了，它都会被记录下来……这些都会加到您的奖金中。 这意味着，如果您之前赢过 3 次，然后又赢了，您将获得 4 美元而不是 1 美元，依此类推……而且不一定是连胜。",
    ", and if it's on the third try, it's": "，如果是第三次尝试，它是",
    ", it's the best bar in town. Let's go inside, I'll show you something.": "，这是镇上最好的酒吧。 我们进去吧，我给你看样东西。",
    ". If on second try, it's": ". 如果第二次尝试，它是",
    ". If you can guess it correctly, you win, cash straight to your pocket.": ". 如果你猜对了，你就赢了，现金直接到你的口袋里。",
    ". That's it, no multiplier for the last 2 guesses, but remember, if you've won before, it will still add up to the total prize.": ". 就是这样，最后 2 次猜测没有乘数，但请记住，如果您以前赢过，它仍然会加到总奖金中。",
    "Alright bro, we're here. This is the": "好的，兄弟，我们到了。 这是",
    "And if I lose?": "如果我输了？",
    "Anything else I should know?": "还有什么我应该知道的吗？",
    "But then I was so broke I decided to give it a try... It did help me pay the bills and some of my student loans...": "但后来我破产了，我决定试一试……它确实帮助我支付了账单和一些学生贷款……",
    "Doesn't sound easy money.": "听起来不容易赚钱。",
    "Follow Hamlet": "跟随哈姆雷特",
    "from": "从",
    "Hmm...": "唔...",
    "How do I play it?": "怎么玩？",
    "I don't really gamble, bro.": "我真的不赌博，兄弟。",
    "I think I get it now.": "我想我现在明白了。",
    "I'll do my best.": "我将尽我所能。",
    "I'm ready but...": "我准备好了但是...",
    "in just": "在短短",
    "Just don't lose it all, alright?": "只是不要失去一切，好吗？",
    "Look, you see those gaming tables over there?": "看，你看到那边的那些赌桌了吗？",
    "multiplied by 3": "乘以3",
    "multiplied by 4": "乘以4",
    "multiplied by 5": "乘以5",
    "Now now... I know that you probably don't have a dollar to your name, right? So here's 20 bucks... you can pay it back to me later if you want.": "现在，现在……我知道你名下可能没有一美元，对吧？ 所以这是 20 美元……如果你愿意，可以稍后还给我。",
    "Okay, so the mechanics is simple... you try to guess the": "好的，所以机制很简单......你试着猜测",
    "Okay, tell me about it.": "好的，告诉我吧。",
    "Raze": "摧毁",
    "RAZE": "摧毁",
    "secret number": "密码",
    "That sounds easy!": "这听起来很简单！",
    "That's the craze 'round here. A real money-making machine... that is if you're smart enough to crack it. And that's why you see a lot of people coming and going.": "这就是这里的热潮。 一台真正的赚钱机器……前提是你足够聪明，可以破解它。 这就是为什么你会看到很多人来来往往。",
    "to": "到",
    "To play it, you have to pay a dollar. If you lose, dollar's gone, and if you win, you earn one back.": "要玩它，您必须支付一美元。 如果你输了，美元就没了，如果你赢了，你就赚回来了。",
    "Well, I understand you. I was just like you.": "好吧，我理解你。 我和你一样。",
    "What d'you think?": "你觉得呢？",
    "What's going on?": "这是怎么回事？",
    "Yeah...": "是的...",
    "You're the best, Ham.": "你是最棒的，汉姆。",
    "Yup, to add to up to that, if you got it right in your first guess, your prize is": "是的，加起来，如果你第一次猜对了，你的奖品是",
    "You earned💲": "你赢了💲",
    "You won in third try! Way to go! 🤩": "您在第三次尝试中获胜！ 干得好！ 🤩",
    "Your guess is low.": "你猜测的数字低了。",
    "Your guess is too low!": "你猜测的数字太低了！",
    "GAME 😭 OVER": "游戏 😭 结束",
    "The secret number is": "秘密数字是",
    "Your guess is a bit higher.": "你猜测的数字有一点高。",
    "Your guess is a bit lower.": "你猜测的数字有一点低。",
    "Your guess is too high!": "你猜测的数字太高了！",
    "Your guess is high.": "你猜测的数字高了。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Total Games Played: ": "玩过的游戏总数：",
    "Remaining Guesses: ": "剩余猜测次数：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\[([\d\.]+)\]$/,
    /^⚡([\d\.]+)$/,
    /^💲([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) tries$/, '$1 尝试'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);